### ISSUE TITLE
Sieve not working with PHP8

### ISSUE THREAD

**Issue by darthmaul0181** [afterlogic/MailSo#4]
It seems Sieve is not working with PHP8:

AH01071: Got error 'PHP message: PHP Warning:  Declaration of MailSo\\Sieve\\ManageSieveClient::Connect($sServerName, $iPort, $iSecurityType = MailSo\\Net\\Enumerations\\ConnectionSecurityType::AUTO_DETECT, $bVerifySsl = false, $bAllowSelfSigned = true) should be compatible with MailSo\\Net\\NetClient::Connect($sServerName, $iPort, $iSecurityType = MailSo\\Net\\Enumerations\\ConnectionSecurityType::AUTO_DETECT, $bVerifySsl = false, $bAllowSelfSigned = true, $sClientCert = '') in /data/www/admin/html/rainloop/rainloop/v/1.15.0/app/libraries/MailSo/Sieve/ManageSieveClient.php on line 114'

**Comment by afterlogic-support** [comment]
> ... /data/www/admin/html/rainloop/rainloop/v/1.15.0/ ...

That doesn't look addressed to us, sorry.

**Comment by afterlogic-support** [comment]
We will, however, recheck whether this functionality of our product works correctly with PHP v8. Thanks.

**Comment by afterlogic-support** [comment]
Have just rechecked this with the latest WebMail version; indeed, there's an error when PHP 8 is used (though the error itself is different). Have reported it to the developers. Thank you.

For those running into the issue with Afterlogic Webmail, line ~304 in `vendor/afterlogic/mailso/lib/MailSo/Sieve/ManageSieveClient.php` file:
```php
if ('{' === $mResponse[0]{0})
```

needs to be replaced with:
```php
if ('{' === substr($mResponse[0],0,1))
```
