### ISSUE TITLE
IMAP: x-originating-ip

### ISSUE THREAD

**Issue by bnchdan** [afterlogic/MailSo#7]
Hi,

This module is provided and I am using it in aurora webmail. 

My question is if is a method to send the command :
https://doc.dovecot.org/configuration_manual/forwarding_parameters/#imap-protocol
```
[tag] ID ("x-originating-ip" "{client ip}")
```
before the command LOGIN in the Imap login process (https://github.com/afterlogic/MailSo/blob/cae67fc69bb8f8c8ea2280a806655326117d4b20/lib/MailSo/Imap/ImapClient.php#L194).

**Comment by afterlogic-support** [comment]
Please locate the following line ~109 in `modules/Mail/Managers/Main/Manager.php` file:

```php
if (!$oResult->IsLoggined()) {
```

and add the following code right after it:

```php
$oResult->SendRequestWithCheck('ID', array('("x-originating-ip" "'.\Aurora\System\Utils::getClientIp().'")'));
```

Hope this helps. We will consider adding this into the regular release of the product.

**Comment by bnchdan** [comment]
It works. Thanks.
